name: Build RS-backend

on:
  push:
    tags:
      - 'v*'          # 打 tag 时触发
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build RS-backend
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" == "windows" ]; then
            EXT=".exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/RS-backend-${{ matrix.goos }}-${{ matrix.goarch }}$EXT main.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RS-backend-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/
