name: Build & Release RS-backend

on:
  push:
    tags:
      - 'v*'          # 打 tag 时触发，例如 v1.0.0
  workflow_dispatch:  # 手动触发

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
      # 1️⃣ 获取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 安装 Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # 3️⃣ 构建可执行文件
      - name: Build RS-backend
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" == "windows" ]; then
            EXT=".exe"
          fi
          echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/RS-backend-${{ matrix.goos }}-${{ matrix.goarch }}$EXT main.go

      # 4️⃣ 上传构建产物（可用于调试或下载）
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RS-backend-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  # 5️⃣ Release job（等构建完成后运行）
  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 6️⃣ 创建 GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "RS-backend ${{ github.ref_name }}"
          draft: false
          prerelease: false

      # 7️⃣ 上传所有构建产物到 Release
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
