name: Build & Upload to Specific Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name to build (must exist in repo, e.g. v1.0.2)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code for specific tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build binaries
        run: |
          mkdir -p dist
          echo "🔨 Building for Linux amd64..."
          GOOS=linux GOARCH=amd64 go build -o dist/RS-backend-linux-amd64 ./main.go
          echo "🔨 Building for Windows amd64..."
          GOOS=windows GOARCH=amd64 go build -o dist/RS-backend-windows-amd64.exe ./main.go

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          body: |
            🔧 Updated binaries for **${{ github.event.inputs.tag }}**
            - RS-backend (Linux amd64)
            - RS-backend (Windows amd64)
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
